---
--- Generated by Luanalysis
--- Created by chaochao.
--- DateTime: 2023-10-21 17:39
---
local db_num = KEYS[3]
local set_key = KEYS[1]
local lock_key = "Lock"..KEYS[1]
local run_key = KEYS[2]
local lock_timeout = ARGV[1]
local expire_time = ARGV[2]
local page_size = 10

redis.call('select', db_num)

if redis.call("set", lock_key, 1, "nx", "px", lock_timeout) then
  local cursor = '0'
  local count = 0
  repeat

    local result = redis.call('sscan', set_key, cursor, 'COUNT', page_size)
    cursor = result[1]
    local members = result[2]

    for _,task_id in ipairs(members) do
      count = count + 1
      local score = redis.call('zscore', run_key, task_id)

      if not score then
        redis.call('zadd', run_key, expire_time, task_id)
        redis.call("del", lock_key)
        return task_id
      end

    end

  until cursor == '0' or count > 10

  redis.call("del", lock_key)

end

return nil