---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Chaocc123.
--- DateTime: 2023/11/16 10:48
---
---
local hash_key = KEYS[1]
local db_num = KEYS[2]
local death_key = ARGV[1]
local task_id = ARGV[2]

redis.call('select', db_num)
local task_body = redis.call('HGET',hash_key, task_id)
if task_body then
        local s1 = redis.call('LPUSH', death_key, task_body)
        return s1
end


